# Generated by Django 4.2.8 on 2025-11-28 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ItemApp', '0003_datotributario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registronuam',
            name='pais',
            field=models.CharField(choices=[('chile', 'Chile'), ('colombia', 'Colombia'), ('peru', 'Perú'), ('argentina', 'Argentina'), ('mexico', 'México'), ('brasil', 'Brasil'), ('ecuador', 'Ecuador'), ('venezuela', 'Venezuela'), ('uruguay', 'Uruguay'), ('paraguay', 'Paraguay'), ('bolivia', 'Bolivia')], max_length=100),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('corredor', 'Corredor'), ('tributario', 'Tributario')], default='corredor', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.CreateModel(
            name='CalificacionTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercado', models.CharField(choices=[('AC', 'AC'), ('ACCIONES', 'ACCIONES'), ('BONOS', 'BONOS'), ('FUTUROS', 'FUTUROS')], default='AC', max_length=50)),
                ('instrumento', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_pago', models.DateField()),
                ('secuencia_evento', models.CharField(max_length=50, unique=True)),
                ('dividendo', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('valor_historico', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('factor_actualizacion', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('año', models.IntegerField()),
                ('isfut', models.BooleanField(default=False)),
                ('origen', models.CharField(choices=[('CORREDOR', 'CORREDOR'), ('TRIBUTARIO', 'TRIBUTARIO'), ('ADMIN', 'ADMIN')], default='CORREDOR', max_length=50)),
                ('calificacion_pendiente', models.BooleanField(default=False)),
                ('periodo_comercial', models.IntegerField(blank=True, null=True)),
                ('evento_capital', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('factor_08', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='Con crédito por IDPC generados a contar del 01.01.2017')),
                ('factor_09', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='Con crédito por IDPC acumulados hasta el 31.12.2016')),
                ('factor_10', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='Con derecho a crédito por pago IDPC Voluntario')),
                ('factor_11', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='Sin derecho a credito')),
                ('factor_12', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='Impto. 1ra Categ. Exento Gl Comp. Con Devolución')),
                ('factor_13', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='Impto. 1ra Categ. Afecto Gl Comp. Sin Devolución')),
                ('factor_14', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='Impto. 1ra Categ. Exento Gl Comp. Sin Devolución')),
                ('factor_15', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='Impto. Créditos pro Impuestos Externos')),
                ('factor_16', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='No Constitutiva de Renta Acogido a Impto.')),
                ('factor_17', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='No Constitutiva de Renta Devolución de Capital Art.17')),
                ('factor_18', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='Rentas Exentas de Impto. GC Y/O Impto Adicional')),
                ('factor_19', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='Ingreso no Constitutivos de Renta')),
                ('factor_20', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='Sin Derecho a Devolucion')),
                ('factor_21', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='Con Derecho a Devolucion')),
                ('factor_22', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='Sin Derecho a Devolucion')),
                ('factor_23', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='Con Derecho a Devolucion')),
                ('factor_24', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='Sin Derecho a Devolucion')),
                ('factor_25', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='Con Derecho a Devolucion')),
                ('factor_26', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='Sin Derecho a Devolucion')),
                ('factor_27', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='Con Derecho a Devolucion')),
                ('factor_28', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='Credito por IPE')),
                ('factor_29', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='Sin Derecho a Devolucion')),
                ('factor_30', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='Con Derecho a Devolucion')),
                ('factor_31', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='Sin Derecho a Devolucion')),
                ('factor_32', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='Con Derecho a Devolucion')),
                ('factor_33', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='Credito por IPE')),
                ('factor_34', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='Cred. Por Impto. Tasa Adicional, Ex Art. 21 UR')),
                ('factor_35', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='Tasa Efectiva Del Cred. Del FUT (TEF)')),
                ('factor_36', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='TASA EFECTIVA DEL CRED. DEL FUNT (TEX)')),
                ('factor_37', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='DEVOLUCION DE CAPITAL ART. 17 NUM 7 UR')),
                ('factor_198', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='Ingreso no Constitutivos de Renta')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calificación Tributaria',
                'verbose_name_plural': 'Calificaciones Tributarias',
                'ordering': ['-año', '-fecha_pago', 'instrumento'],
                'indexes': [models.Index(fields=['año', 'instrumento'], name='ItemApp_cal_año_434a39_idx'), models.Index(fields=['mercado', 'origen'], name='ItemApp_cal_mercado_a60486_idx'), models.Index(fields=['calificacion_pendiente'], name='ItemApp_cal_calific_d24274_idx')],
            },
        ),
    ]
